apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: cicd
description: CICD delivery pipeline for GKE
serialPipeline:
  stages:
    - targetId: dev
      profiles:
        - dev
    - targetId: prod
      profiles:
        - prod
      requireApproval: true
